# Cleaning Data

Unduh data CSV dari: https://github.com/saadidrees/dataset_covid_19_symptoms/blob/master/dataset_symps_covid19.csv

Import library yang dibutuhkan

In [1]:
import pandas as pd

df = pd.read_csv("dataset_1.csv")

In [2]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1897 entries, 0 to 1896
Data columns (total 16 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   age                      1424 non-null   float64
 1   sex                      1441 non-null   object
 2   country_new              1250 non-null   object
 3   chronic_disease          121 non-null    object
 4   date_onset_symptoms      1162 non-null   object
 5   date_confirmation        1859 non-null   object
 6   date_death_or_discharge  190 non-null    object
 7   outcome                  471 non-null    object
 8   Fever                    1897 non-null   float64
 9   Cough                    1897 non-null   float64
 10  Fatigue                  1897 non-null   float64
 11  Sore throat              1897 non-null   float64
 12  Runny nose               1897 non-null   float64
 13  Shortness of breath      1897 non-null   int64
 14  Vomiting                 1897 non-null   float64
 15  full_symptoms            1896 non-null   object
dtypes: float64(7), int64(1), object(8)
memory usage: 237.2+ KB

In [3]:
df.describe()

,age,Fever,Cough,Fatigue,Sore throat,Runny nose,Shortness of breath,Vomiting
count,1424.000000,1897.000000,1897.000000,1897.000000,1897.000000,1897.000000,1897.000000,1897.000000
mean,50.516503,0.569953,0.316342,0.117080,0.064365,0.044386,0.042172,0.016078
std,18.645291,1.328923,0.823627,0.403183,0.276879,0.222546,0.216203,0.127371
min,0.250000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,36.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
50%,52.000000,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
75%,65.000000,1.000000,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000
max,96.000000,54.200000,30.100000,11.100000,6.100000,4.200000,4.000000,1.500000

In [4]:
df.head()

,age,sex,country_new,chronic_disease,date_onset_symptoms,date_confirmation,date_death_or_discharge,outcome,Fever,Cough,Fatigue,Sore throat,Runny nose,Shortness of breath,Vomiting,full_symptoms
0,60.0,male,Japan,NaN,03.02.2020,18.02.2020,NaN,NaN,1.0,0.0,0.0,0.0,0.0,0,0.0,"fever, severe pneumonia"
1,45.0,male,Japan,NaN,08.02.2020,10.02.2020,NaN,NaN,1.0,0.0,0.0,0.0,0.0,0,0.0,fever
2,25.0,male,Japan,NaN,07.02.2020,08.02.2020,NaN,NaN,1.0,1.0,0.0,1.0,0.0,0,0.0,"cough, fever, sore throat"
3,45.0,male,Japan,NaN,02.02.2020,15.02.2020,NaN,NaN,1.0,1.0,0.0,0.0,0.0,0,0.0,"cough, fever"
4,85.0,male,Japan,NaN,09.02.2020,18.02.2020,NaN,NaN,1.0,0.0,0.0,0.0,0.0,1,0.0,"dyspnea, fever"

Hapus kolom yang tidak dibutuhkan

In [5]:
hapus_kolom = ['country_new','chronic_disease','date_onset_symptoms','full_symptoms']

In [6]:
df.drop(hapus_kolom, inplace=True, axis=1)

In [7]:
df.head()

,age,sex,date_confirmation,date_death_or_discharge,outcome,Fever,Cough,Fatigue,Sore throat,Runny nose,Shortness of breath,Vomiting
0,60.0,male,18.02.2020,NaN,NaN,1.0,0.0,0.0,0.0,0.0,0,0.0
1,45.0,male,10.02.2020,NaN,NaN,1.0,0.0,0.0,0.0,0.0,0,0.0
2,25.0,male,08.02.2020,NaN,NaN,1.0,1.0,0.0,1.0,0.0,0,0.0
3,45.0,male,15.02.2020,NaN,NaN,1.0,1.0,0.0,0.0,0.0,0,0.0
4,85.0,male,18.02.2020,NaN,NaN,1.0,0.0,0.0,0.0,0.0,1,0.0

Hapus semua baris yang memiliki missing value

In [8]:
df.isnull().sum()

age                         473
sex                         456
date_confirmation            38
date_death_or_discharge    1707
outcome                    1426
Fever                         0
Cough                         0
Fatigue                       0
Sore throat                   0
Runny nose                    0
Shortness of breath           0
Vomiting                      0
dtype: int64

In [9]:
df.dropna(axis=0, inplace=True)

In [10]:
df.head()

,age,sex,date_confirmation,date_death_or_discharge,outcome,Fever,Cough,Fatigue,Sore throat,Runny nose,Shortness of breath,Vomiting
132,44.0,female,21.01.2020,29.01.2020,discharged,1.0,0.0,1.0,0.0,0.0,0,0.0
136,39.0,female,24.01.2020,03.02.2020,discharged,1.0,0.0,1.0,0.0,1.0,0,0.0
170,30.0,male,15.01.2020,15.01.2020,discharged,1.0,1.0,0.0,1.0,0.0,0,0.0
183,32.0,male,24.01.2020,17.01.2020,discharged,1.0,1.0,0.0,0.0,0.0,1,0.0
184,66.0,male,23.01.2020,19.02.2020,discharged,1.0,1.0,0.0,0.0,0.0,0,0.0

In [11]:
df.shape

(148, 12)

Hapus baris yang mengandung died, death, dead, deceased (kolom outcome)

In [12]:
df['outcome'].value_counts()

died          87
discharge     23
discharged    15
recovered     10
death          8
Discharged     2
dead           2
Deceased       1
Name: outcome, dtype: int64

In [13]:
died = df[(df['outcome'] == 'died')].index
df.drop(died, inplace=True)

In [14]:
death = df[(df['outcome'] == 'death')].index
df.drop(death, inplace=True)

In [15]:
died = df[(df['outcome'] == 'dead')].index
df.drop(died, inplace=True)

In [16]:
deceased = df[(df['outcome'] == 'Deceased')].index
df.drop(deceased, inplace=True)

Hapus kolom outcome, karena sudah dibersihkan dan tersisa tanggal pasien sembuh

In [17]:
df.drop('outcome', axis=1, inplace=True)

In [18]:
df

,age,sex,date_confirmation,date_death_or_discharge,Fever,Cough,Fatigue,Sore throat,Runny nose,Shortness of breath,Vomiting
132,44.00,female,21.01.2020,29.01.2020,1.0,0.0,1.0,0.0,0.0,0,0.0
136,39.00,female,24.01.2020,03.02.2020,1.0,0.0,1.0,0.0,1.0,0,0.0
170,30.00,male,15.01.2020,15.01.2020,1.0,1.0,0.0,1.0,0.0,0,0.0
183,32.00,male,24.01.2020,17.01.2020,1.0,1.0,0.0,0.0,0.0,1,0.0
184,66.00,male,23.01.2020,19.02.2020,1.0,1.0,0.0,0.0,0.0,0,0.0
185,40.00,male,25.01.2020,08.02.2020,1.0,1.0,0.0,0.0,0.0,0,0.0
187,33.00,male,27.01.2020,27.01.2020,1.0,0.0,1.0,1.0,0.0,0,0.0
212,1.00,female,08.02.2020,17.02.2020,0.0,0.0,0.0,0.0,0.0,0,0.0
217,30.00,female,24.01.2020,12.02.2020,1.0,1.0,1.0,0.0,0.0,0,0.0
218,31.00,male,24.01.2020,12.02.2020,1.0,1.0,0.0,0.0,0.0,0,0.0
438,29.00,male,24.01.2020,28.01.2020,0.0,0.0,0.0,0.0,0.0,0,0.0
477,55.00,male,24.01.2020,05.02.2020,1.0,0.0,0.0,0.0,0.0,0,0.0
580,73.00,male,02.02.2020,21.02.2020,0.0,0.0,0.0,0.0,0.0,0,0.0
601,42.00,female,04.02.2020,20.02.2020,1.0,1.0,0.0,0.0,1.0,0,0.0
607,28.00,female,03.02.2020,22.02.2020,1.0,0.0,0.0,1.0,0.0,0,0.0
623,49.00,female,06.02.2020,20.02.2020,0.0,1.0,0.0,0.0,0.0,0,0.0
625,16.00,female,06.02.2020,20.02.2020,1.0,1.0,0.0,0.0,0.0,0,0.0
650,29.00,male,06.02.2020,22.02.2020,1.0,0.0,0.0,0.0,0.0,0,0.0
651,55.00,female,09.02.2020,18.02.2020,1.0,0.0,0.0,0.0,1.0,0,0.0
652,0.25,female,11.02.2020,20.02.2020,0.0,1.0,0.0,0.0,1.0,0,0.0
658,50.00,male,13.02.2020,26.02.2020,0.0,0.0,1.0,0.0,0.0,0,0.0
702,61.00,male,14.02.2020,26.02.2020,1.0,0.0,0.0,0.0,0.0,0,0.0
1162,55.00,female,09.02.2020,18.02.2020,1.0,0.0,0.0,0.0,1.0,0,0.0
1163,0.25,female,11.02.2020,20.02.2020,0.0,1.0,0.0,0.0,1.0,0,0.0
1164,50.00,male,13.02.2020,26.02.2020,0.0,0.0,1.0,0.0,0.0,0,0.0
1181,61.00,male,14.02.2020,26.02.2020,1.0,0.0,0.0,0.0,0.0,0,0.0
1411,29.00,male,24.01.2020,28.01.2020,0.0,0.0,0.0,0.0,0.0,0,0.0
1445,72.00,male,09.03.2020,27.03.2020,0.0,1.0,0.0,0.0,0.0,0,0.0
1448,34.00,male,09.03.2020,15.03.2020,1.0,0.0,0.0,0.0,0.0,0,0.0
1449,46.00,male,09.03.2020,15.03.2020,1.0,1.0,0.0,0.0,0.0,0,0.0
1450,70.00,male,09.03.2020,19.03.2020,1.0,1.0,0.0,1.0,0.0,0,0.0
1451,41.00,male,09.03.2020,24.03.2020,1.0,0.0,0.0,0.0,0.0,0,0.0
1452,46.00,female,09.03.2020,26.03.2020,0.0,0.0,0.0,0.0,0.0,0,0.0
1455,51.00,female,09.03.2020,18.03.2020,1.0,1.0,0.0,0.0,0.0,0,0.0
1457,30.00,female,09.03.2020,24.03.2020,0.0,1.0,0.0,1.0,0.0,0,0.0
1458,31.00,male,09.03.2020,17.03.2020,0.0,0.0,0.0,0.0,0.0,0,0.0
1459,34.00,male,10.03.2020,17.03.2020,0.0,0.0,0.0,0.0,0.0,0,0.0
1638,39.00,female,24.01.2020,03.02.2020,1.0,0.0,1.0,0.0,1.0,0,0.0
1658,73.00,male,02.02.2020,21.02.2020,0.0,0.0,0.0,0.0,0.0,0,0.0
1708,42.00,female,04.02.2020,20.02.2020,1.0,1.0,0.0,0.0,1.0,0,0.0
1709,28.00,female,03.02.2020,22.02.2020,1.0,0.0,0.0,1.0,0.0,0,0.0
1717,44.00,female,21.01.2020,29.01.2020,1.0,0.0,1.0,0.0,0.0,0,0.0
1721,49.00,female,06.02.2020,20.02.2020,0.0,1.0,0.0,0.0,0.0,0,0.0
1722,16.00,female,06.02.2020,20.02.2020,1.0,1.0,0.0,0.0,0.0,0,0.0
1766,30.00,male,15.01.2020,15.01.2020,1.0,1.0,0.0,1.0,0.0,0,0.0
1768,32.00,male,24.01.2020,17.01.2020,1.0,1.0,0.0,0.0,0.0,1,0.0
1769,66.00,male,23.01.2020,19.02.2020,1.0,1.0,0.0,0.0,0.0,0,0.0
1772,55.00,male,24.01.2020,05.02.2020,1.0,0.0,0.0,0.0,0.0,0,0.0
1776,40.00,male,25.01.2020,08.02.2020,1.0,1.0,0.0,0.0,0.0,0,0.0
1798,1.00,female,08.02.2020,17.02.2020,0.0,0.0,0.0,0.0,0.0,0,0.0

Rename nama kolom date_death_or_discharge menjadi date_recovered, karena sudah dibersihkan dan tersisa tanggal pasien sembuh

In [19]:
df.rename(
    columns={'date_death_or_discharge': 'date_recovered'}, 
    inplace=True,
)

In [20]:
df.head()

,age,sex,date_confirmation,date_recovered,Fever,Cough,Fatigue,Sore throat,Runny nose,Shortness of breath,Vomiting
132,44.0,female,21.01.2020,29.01.2020,1.0,0.0,1.0,0.0,0.0,0,0.0
136,39.0,female,24.01.2020,03.02.2020,1.0,0.0,1.0,0.0,1.0,0,0.0
170,30.0,male,15.01.2020,15.01.2020,1.0,1.0,0.0,1.0,0.0,0,0.0
183,32.0,male,24.01.2020,17.01.2020,1.0,1.0,0.0,0.0,0.0,1,0.0
184,66.0,male,23.01.2020,19.02.2020,1.0,1.0,0.0,0.0,0.0,0,0.0

Mengubah index sesuai default

In [21]:
df.reset_index(drop=True, inplace=True)

In [22]:
df.head()

,age,sex,date_confirmation,date_recovered,Fever,Cough,Fatigue,Sore throat,Runny nose,Shortness of breath,Vomiting
0,44.0,female,21.01.2020,29.01.2020,1.0,0.0,1.0,0.0,0.0,0,0.0
1,39.0,female,24.01.2020,03.02.2020,1.0,0.0,1.0,0.0,1.0,0,0.0
2,30.0,male,15.01.2020,15.01.2020,1.0,1.0,0.0,1.0,0.0,0,0.0
3,32.0,male,24.01.2020,17.01.2020,1.0,1.0,0.0,0.0,0.0,1,0.0
4,66.0,male,23.01.2020,19.02.2020,1.0,1.0,0.0,0.0,0.0,0,0.0

Mengubah value dari kolom sex menjadi 1 untuk male dan 0 untuk female

In [23]:
def changetobiner(df):
    if df == 'male':
        df = 1
    else:
        df = 0  
    
    return df
  
sex = []
for index, row in df.iterrows():
    sex.append(changetobiner(row['sex']))

df['sex'] = sex

In [24]:
df

,age,sex,date_confirmation,date_recovered,Fever,Cough,Fatigue,Sore throat,Runny nose,Shortness of breath,Vomiting
0,44.00,0,21.01.2020,29.01.2020,1.0,0.0,1.0,0.0,0.0,0,0.0
1,39.00,0,24.01.2020,03.02.2020,1.0,0.0,1.0,0.0,1.0,0,0.0
2,30.00,1,15.01.2020,15.01.2020,1.0,1.0,0.0,1.0,0.0,0,0.0
3,32.00,1,24.01.2020,17.01.2020,1.0,1.0,0.0,0.0,0.0,1,0.0
4,66.00,1,23.01.2020,19.02.2020,1.0,1.0,0.0,0.0,0.0,0,0.0
5,40.00,1,25.01.2020,08.02.2020,1.0,1.0,0.0,0.0,0.0,0,0.0
6,33.00,1,27.01.2020,27.01.2020,1.0,0.0,1.0,1.0,0.0,0,0.0
7,1.00,0,08.02.2020,17.02.2020,0.0,0.0,0.0,0.0,0.0,0,0.0
8,30.00,0,24.01.2020,12.02.2020,1.0,1.0,1.0,0.0,0.0,0,0.0
9,31.00,1,24.01.2020,12.02.2020,1.0,1.0,0.0,0.0,0.0,0,0.0
10,29.00,1,24.01.2020,28.01.2020,0.0,0.0,0.0,0.0,0.0,0,0.0
11,55.00,1,24.01.2020,05.02.2020,1.0,0.0,0.0,0.0,0.0,0,0.0
12,73.00,1,02.02.2020,21.02.2020,0.0,0.0,0.0,0.0,0.0,0,0.0
13,42.00,0,04.02.2020,20.02.2020,1.0,1.0,0.0,0.0,1.0,0,0.0
14,28.00,0,03.02.2020,22.02.2020,1.0,0.0,0.0,1.0,0.0,0,0.0
15,49.00,0,06.02.2020,20.02.2020,0.0,1.0,0.0,0.0,0.0,0,0.0
16,16.00,0,06.02.2020,20.02.2020,1.0,1.0,0.0,0.0,0.0,0,0.0
17,29.00,1,06.02.2020,22.02.2020,1.0,0.0,0.0,0.0,0.0,0,0.0
18,55.00,0,09.02.2020,18.02.2020,1.0,0.0,0.0,0.0,1.0,0,0.0
19,0.25,0,11.02.2020,20.02.2020,0.0,1.0,0.0,0.0,1.0,0,0.0
20,50.00,1,13.02.2020,26.02.2020,0.0,0.0,1.0,0.0,0.0,0,0.0
21,61.00,1,14.02.2020,26.02.2020,1.0,0.0,0.0,0.0,0.0,0,0.0
22,55.00,0,09.02.2020,18.02.2020,1.0,0.0,0.0,0.0,1.0,0,0.0
23,0.25,0,11.02.2020,20.02.2020,0.0,1.0,0.0,0.0,1.0,0,0.0
24,50.00,1,13.02.2020,26.02.2020,0.0,0.0,1.0,0.0,0.0,0,0.0
25,61.00,1,14.02.2020,26.02.2020,1.0,0.0,0.0,0.0,0.0,0,0.0
26,29.00,1,24.01.2020,28.01.2020,0.0,0.0,0.0,0.0,0.0,0,0.0
27,72.00,1,09.03.2020,27.03.2020,0.0,1.0,0.0,0.0,0.0,0,0.0
28,34.00,1,09.03.2020,15.03.2020,1.0,0.0,0.0,0.0,0.0,0,0.0
29,46.00,1,09.03.2020,15.03.2020,1.0,1.0,0.0,0.0,0.0,0,0.0
30,70.00,1,09.03.2020,19.03.2020,1.0,1.0,0.0,1.0,0.0,0,0.0
31,41.00,1,09.03.2020,24.03.2020,1.0,0.0,0.0,0.0,0.0,0,0.0
32,46.00,0,09.03.2020,26.03.2020,0.0,0.0,0.0,0.0,0.0,0,0.0
33,51.00,0,09.03.2020,18.03.2020,1.0,1.0,0.0,0.0,0.0,0,0.0
34,30.00,0,09.03.2020,24.03.2020,0.0,1.0,0.0,1.0,0.0,0,0.0
35,31.00,1,09.03.2020,17.03.2020,0.0,0.0,0.0,0.0,0.0,0,0.0
36,34.00,1,10.03.2020,17.03.2020,0.0,0.0,0.0,0.0,0.0,0,0.0
37,39.00,0,24.01.2020,03.02.2020,1.0,0.0,1.0,0.0,1.0,0,0.0
38,73.00,1,02.02.2020,21.02.2020,0.0,0.0,0.0,0.0,0.0,0,0.0
39,42.00,0,04.02.2020,20.02.2020,1.0,1.0,0.0,0.0,1.0,0,0.0
40,28.00,0,03.02.2020,22.02.2020,1.0,0.0,0.0,1.0,0.0,0,0.0
41,44.00,0,21.01.2020,29.01.2020,1.0,0.0,1.0,0.0,0.0,0,0.0
42,49.00,0,06.02.2020,20.02.2020,0.0,1.0,0.0,0.0,0.0,0,0.0
43,16.00,0,06.02.2020,20.02.2020,1.0,1.0,0.0,0.0,0.0,0,0.0
44,30.00,1,15.01.2020,15.01.2020,1.0,1.0,0.0,1.0,0.0,0,0.0
45,32.00,1,24.01.2020,17.01.2020,1.0,1.0,0.0,0.0,0.0,1,0.0
46,66.00,1,23.01.2020,19.02.2020,1.0,1.0,0.0,0.0,0.0,0,0.0
47,55.00,1,24.01.2020,05.02.2020,1.0,0.0,0.0,0.0,0.0,0,0.0
48,40.00,1,25.01.2020,08.02.2020,1.0,1.0,0.0,0.0,0.0,0,0.0
49,1.00,0,08.02.2020,17.02.2020,0.0,0.0,0.0,0.0,0.0,0,0.0

Menambahkan kolom recovery_days

In [25]:
df['date_confirmation'] = df['date_confirmation'].str.replace('.', '-')
df['date_recovered'] = df['date_recovered'].str.replace('.', '-')

<ipython-input-25-de032f38e357>:1: FutureWarning: The default value of regex will change from True to False in a future version. In addition, single character regular expressions will*not* be treated as literal strings when regex=True.
  df['date_confirmation'] = df['date_confirmation'].str.replace('.', '-')
<ipython-input-25-de032f38e357>:2: FutureWarning: The default value of regex will change from True to False in a future version. In addition, single character regular expressions will*not* be treated as literal strings when regex=True.
  df['date_recovered'] = df['date_recovered'].str.replace('.', '-')

In [26]:
df['date_confirmation'] = pd.to_datetime(df['date_confirmation'], format='%d-%m-%Y')
df['date_recovered'] = pd.to_datetime(df['date_recovered'], format='%d-%m-%Y')

df['recovery_days'] = df['date_recovered'] - df['date_confirmation']

In [27]:
df.head()

,age,sex,date_confirmation,date_recovered,Fever,Cough,Fatigue,Sore throat,Runny nose,Shortness of breath,Vomiting,recovery_days
0,44.0,0,2020-01-21,2020-01-29,1.0,0.0,1.0,0.0,0.0,0,0.0,8 days
1,39.0,0,2020-01-24,2020-02-03,1.0,0.0,1.0,0.0,1.0,0,0.0,10 days
2,30.0,1,2020-01-15,2020-01-15,1.0,1.0,0.0,1.0,0.0,0,0.0,0 days
3,32.0,1,2020-01-24,2020-01-17,1.0,1.0,0.0,0.0,0.0,1,0.0,-7 days
4,66.0,1,2020-01-23,2020-02-19,1.0,1.0,0.0,0.0,0.0,0,0.0,27 days

In [28]:
df['recovery_days'].value_counts()

9 days     7
19 days    6
14 days    6
12 days    4
10 days    3
16 days    3
0 days     3
8 days     3
15 days    2
27 days    2
4 days     2
-7 days    2
13 days    2
6 days     2
7 days     1
17 days    1
18 days    1
Name: recovery_days, dtype: int64

Memperbaiki recovery_days yang memiliki nilai minus

In [29]:
df = df.append({'age': 32.00, 'sex': 1, 'date_confirmation': '2020-01-17', 'date_recovered': '2020-01-24', 'Fever': 1.0, 'Cough': 1.0, 'Fatigue': 0.0, 'Sore throat': 0.0, 'Runny nose': 0.0, 'Shortness of breath': 1.0, 'Vomiting': 0.0, 'recovery_days': '17 days'}, ignore_index=True)
df = df.append({'age': 32.00, 'sex': 1, 'date_confirmation': '2020-01-17', 'date_recovered': '2020-01-24', 'Fever': 1.0, 'Cough': 1.0, 'Fatigue': 0.0, 'Sore throat': 0.0, 'Runny nose': 0.0, 'Shortness of breath': 1.0, 'Vomiting': 0.0, 'recovery_days': '17 days'}, ignore_index=True)

In [30]:
df

,age,sex,date_confirmation,date_recovered,Fever,Cough,Fatigue,Sore throat,Runny nose,Shortness of breath,Vomiting,recovery_days
0,44.00,0,2020-01-21 00:00:00,2020-01-29 00:00:00,1.0,0.0,1.0,0.0,0.0,0.0,0.0,8 days 00:00:00
1,39.00,0,2020-01-24 00:00:00,2020-02-03 00:00:00,1.0,0.0,1.0,0.0,1.0,0.0,0.0,10 days 00:00:00
2,30.00,1,2020-01-15 00:00:00,2020-01-15 00:00:00,1.0,1.0,0.0,1.0,0.0,0.0,0.0,0 days 00:00:00
3,32.00,1,2020-01-24 00:00:00,2020-01-17 00:00:00,1.0,1.0,0.0,0.0,0.0,1.0,0.0,-7 days +00:00:00
4,66.00,1,2020-01-23 00:00:00,2020-02-19 00:00:00,1.0,1.0,0.0,0.0,0.0,0.0,0.0,27 days 00:00:00
5,40.00,1,2020-01-25 00:00:00,2020-02-08 00:00:00,1.0,1.0,0.0,0.0,0.0,0.0,0.0,14 days 00:00:00
6,33.00,1,2020-01-27 00:00:00,2020-01-27 00:00:00,1.0,0.0,1.0,1.0,0.0,0.0,0.0,0 days 00:00:00
7,1.00,0,2020-02-08 00:00:00,2020-02-17 00:00:00,0.0,0.0,0.0,0.0,0.0,0.0,0.0,9 days 00:00:00
8,30.00,0,2020-01-24 00:00:00,2020-02-12 00:00:00,1.0,1.0,1.0,0.0,0.0,0.0,0.0,19 days 00:00:00
9,31.00,1,2020-01-24 00:00:00,2020-02-12 00:00:00,1.0,1.0,0.0,0.0,0.0,0.0,0.0,19 days 00:00:00
10,29.00,1,2020-01-24 00:00:00,2020-01-28 00:00:00,0.0,0.0,0.0,0.0,0.0,0.0,0.0,4 days 00:00:00
11,55.00,1,2020-01-24 00:00:00,2020-02-05 00:00:00,1.0,0.0,0.0,0.0,0.0,0.0,0.0,12 days 00:00:00
12,73.00,1,2020-02-02 00:00:00,2020-02-21 00:00:00,0.0,0.0,0.0,0.0,0.0,0.0,0.0,19 days 00:00:00
13,42.00,0,2020-02-04 00:00:00,2020-02-20 00:00:00,1.0,1.0,0.0,0.0,1.0,0.0,0.0,16 days 00:00:00
14,28.00,0,2020-02-03 00:00:00,2020-02-22 00:00:00,1.0,0.0,0.0,1.0,0.0,0.0,0.0,19 days 00:00:00
15,49.00,0,2020-02-06 00:00:00,2020-02-20 00:00:00,0.0,1.0,0.0,0.0,0.0,0.0,0.0,14 days 00:00:00
16,16.00,0,2020-02-06 00:00:00,2020-02-20 00:00:00,1.0,1.0,0.0,0.0,0.0,0.0,0.0,14 days 00:00:00
17,29.00,1,2020-02-06 00:00:00,2020-02-22 00:00:00,1.0,0.0,0.0,0.0,0.0,0.0,0.0,16 days 00:00:00
18,55.00,0,2020-02-09 00:00:00,2020-02-18 00:00:00,1.0,0.0,0.0,0.0,1.0,0.0,0.0,9 days 00:00:00
19,0.25,0,2020-02-11 00:00:00,2020-02-20 00:00:00,0.0,1.0,0.0,0.0,1.0,0.0,0.0,9 days 00:00:00
20,50.00,1,2020-02-13 00:00:00,2020-02-26 00:00:00,0.0,0.0,1.0,0.0,0.0,0.0,0.0,13 days 00:00:00
21,61.00,1,2020-02-14 00:00:00,2020-02-26 00:00:00,1.0,0.0,0.0,0.0,0.0,0.0,0.0,12 days 00:00:00
22,55.00,0,2020-02-09 00:00:00,2020-02-18 00:00:00,1.0,0.0,0.0,0.0,1.0,0.0,0.0,9 days 00:00:00
23,0.25,0,2020-02-11 00:00:00,2020-02-20 00:00:00,0.0,1.0,0.0,0.0,1.0,0.0,0.0,9 days 00:00:00
24,50.00,1,2020-02-13 00:00:00,2020-02-26 00:00:00,0.0,0.0,1.0,0.0,0.0,0.0,0.0,13 days 00:00:00
25,61.00,1,2020-02-14 00:00:00,2020-02-26 00:00:00,1.0,0.0,0.0,0.0,0.0,0.0,0.0,12 days 00:00:00
26,29.00,1,2020-01-24 00:00:00,2020-01-28 00:00:00,0.0,0.0,0.0,0.0,0.0,0.0,0.0,4 days 00:00:00
27,72.00,1,2020-03-09 00:00:00,2020-03-27 00:00:00,0.0,1.0,0.0,0.0,0.0,0.0,0.0,18 days 00:00:00
28,34.00,1,2020-03-09 00:00:00,2020-03-15 00:00:00,1.0,0.0,0.0,0.0,0.0,0.0,0.0,6 days 00:00:00
29,46.00,1,2020-03-09 00:00:00,2020-03-15 00:00:00,1.0,1.0,0.0,0.0,0.0,0.0,0.0,6 days 00:00:00
30,70.00,1,2020-03-09 00:00:00,2020-03-19 00:00:00,1.0,1.0,0.0,1.0,0.0,0.0,0.0,10 days 00:00:00
31,41.00,1,2020-03-09 00:00:00,2020-03-24 00:00:00,1.0,0.0,0.0,0.0,0.0,0.0,0.0,15 days 00:00:00
32,46.00,0,2020-03-09 00:00:00,2020-03-26 00:00:00,0.0,0.0,0.0,0.0,0.0,0.0,0.0,17 days 00:00:00
33,51.00,0,2020-03-09 00:00:00,2020-03-18 00:00:00,1.0,1.0,0.0,0.0,0.0,0.0,0.0,9 days 00:00:00
34,30.00,0,2020-03-09 00:00:00,2020-03-24 00:00:00,0.0,1.0,0.0,1.0,0.0,0.0,0.0,15 days 00:00:00
35,31.00,1,2020-03-09 00:00:00,2020-03-17 00:00:00,0.0,0.0,0.0,0.0,0.0,0.0,0.0,8 days 00:00:00
36,34.00,1,2020-03-10 00:00:00,2020-03-17 00:00:00,0.0,0.0,0.0,0.0,0.0,0.0,0.0,7 days 00:00:00
37,39.00,0,2020-01-24 00:00:00,2020-02-03 00:00:00,1.0,0.0,1.0,0.0,1.0,0.0,0.0,10 days 00:00:00
38,73.00,1,2020-02-02 00:00:00,2020-02-21 00:00:00,0.0,0.0,0.0,0.0,0.0,0.0,0.0,19 days 00:00:00
39,42.00,0,2020-02-04 00:00:00,2020-02-20 00:00:00,1.0,1.0,0.0,0.0,1.0,0.0,0.0,16 days 00:00:00
40,28.00,0,2020-02-03 00:00:00,2020-02-22 00:00:00,1.0,0.0,0.0,1.0,0.0,0.0,0.0,19 days 00:00:00
41,44.00,0,2020-01-21 00:00:00,2020-01-29 00:00:00,1.0,0.0,1.0,0.0,0.0,0.0,0.0,8 days 00:00:00
42,49.00,0,2020-02-06 00:00:00,2020-02-20 00:00:00,0.0,1.0,0.0,0.0,0.0,0.0,0.0,14 days 00:00:00
43,16.00,0,2020-02-06 00:00:00,2020-02-20 00:00:00,1.0,1.0,0.0,0.0,0.0,0.0,0.0,14 days 00:00:00
44,30.00,1,2020-01-15 00:00:00,2020-01-15 00:00:00,1.0,1.0,0.0,1.0,0.0,0.0,0.0,0 days 00:00:00
45,32.00,1,2020-01-24 00:00:00,2020-01-17 00:00:00,1.0,1.0,0.0,0.0,0.0,1.0,0.0,-7 days +00:00:00
46,66.00,1,2020-01-23 00:00:00,2020-02-19 00:00:00,1.0,1.0,0.0,0.0,0.0,0.0,0.0,27 days 00:00:00
47,55.00,1,2020-01-24 00:00:00,2020-02-05 00:00:00,1.0,0.0,0.0,0.0,0.0,0.0,0.0,12 days 00:00:00
48,40.00,1,2020-01-25 00:00:00,2020-02-08 00:00:00,1.0,1.0,0.0,0.0,0.0,0.0,0.0,14 days 00:00:00
49,1.00,0,2020-02-08 00:00:00,2020-02-17 00:00:00,0.0,0.0,0.0,0.0,0.0,0.0,0.0,9 days 00:00:00
50,32.00,1,2020-01-17,2020-01-24,1.0,1.0,0.0,0.0,0.0,1.0,0.0,17 days
51,32.00,1,2020-01-17,2020-01-24,1.0,1.0,0.0,0.0,0.0,1.0,0.0,17 days

In [31]:
df.drop([3, 45], axis=0, inplace=True)

In [32]:
df

,age,sex,date_confirmation,date_recovered,Fever,Cough,Fatigue,Sore throat,Runny nose,Shortness of breath,Vomiting,recovery_days
0,44.00,0,2020-01-21 00:00:00,2020-01-29 00:00:00,1.0,0.0,1.0,0.0,0.0,0.0,0.0,8 days 00:00:00
1,39.00,0,2020-01-24 00:00:00,2020-02-03 00:00:00,1.0,0.0,1.0,0.0,1.0,0.0,0.0,10 days 00:00:00
2,30.00,1,2020-01-15 00:00:00,2020-01-15 00:00:00,1.0,1.0,0.0,1.0,0.0,0.0,0.0,0 days 00:00:00
4,66.00,1,2020-01-23 00:00:00,2020-02-19 00:00:00,1.0,1.0,0.0,0.0,0.0,0.0,0.0,27 days 00:00:00
5,40.00,1,2020-01-25 00:00:00,2020-02-08 00:00:00,1.0,1.0,0.0,0.0,0.0,0.0,0.0,14 days 00:00:00
6,33.00,1,2020-01-27 00:00:00,2020-01-27 00:00:00,1.0,0.0,1.0,1.0,0.0,0.0,0.0,0 days 00:00:00
7,1.00,0,2020-02-08 00:00:00,2020-02-17 00:00:00,0.0,0.0,0.0,0.0,0.0,0.0,0.0,9 days 00:00:00
8,30.00,0,2020-01-24 00:00:00,2020-02-12 00:00:00,1.0,1.0,1.0,0.0,0.0,0.0,0.0,19 days 00:00:00
9,31.00,1,2020-01-24 00:00:00,2020-02-12 00:00:00,1.0,1.0,0.0,0.0,0.0,0.0,0.0,19 days 00:00:00
10,29.00,1,2020-01-24 00:00:00,2020-01-28 00:00:00,0.0,0.0,0.0,0.0,0.0,0.0,0.0,4 days 00:00:00
11,55.00,1,2020-01-24 00:00:00,2020-02-05 00:00:00,1.0,0.0,0.0,0.0,0.0,0.0,0.0,12 days 00:00:00
12,73.00,1,2020-02-02 00:00:00,2020-02-21 00:00:00,0.0,0.0,0.0,0.0,0.0,0.0,0.0,19 days 00:00:00
13,42.00,0,2020-02-04 00:00:00,2020-02-20 00:00:00,1.0,1.0,0.0,0.0,1.0,0.0,0.0,16 days 00:00:00
14,28.00,0,2020-02-03 00:00:00,2020-02-22 00:00:00,1.0,0.0,0.0,1.0,0.0,0.0,0.0,19 days 00:00:00
15,49.00,0,2020-02-06 00:00:00,2020-02-20 00:00:00,0.0,1.0,0.0,0.0,0.0,0.0,0.0,14 days 00:00:00
16,16.00,0,2020-02-06 00:00:00,2020-02-20 00:00:00,1.0,1.0,0.0,0.0,0.0,0.0,0.0,14 days 00:00:00
17,29.00,1,2020-02-06 00:00:00,2020-02-22 00:00:00,1.0,0.0,0.0,0.0,0.0,0.0,0.0,16 days 00:00:00
18,55.00,0,2020-02-09 00:00:00,2020-02-18 00:00:00,1.0,0.0,0.0,0.0,1.0,0.0,0.0,9 days 00:00:00
19,0.25,0,2020-02-11 00:00:00,2020-02-20 00:00:00,0.0,1.0,0.0,0.0,1.0,0.0,0.0,9 days 00:00:00
20,50.00,1,2020-02-13 00:00:00,2020-02-26 00:00:00,0.0,0.0,1.0,0.0,0.0,0.0,0.0,13 days 00:00:00
21,61.00,1,2020-02-14 00:00:00,2020-02-26 00:00:00,1.0,0.0,0.0,0.0,0.0,0.0,0.0,12 days 00:00:00
22,55.00,0,2020-02-09 00:00:00,2020-02-18 00:00:00,1.0,0.0,0.0,0.0,1.0,0.0,0.0,9 days 00:00:00
23,0.25,0,2020-02-11 00:00:00,2020-02-20 00:00:00,0.0,1.0,0.0,0.0,1.0,0.0,0.0,9 days 00:00:00
24,50.00,1,2020-02-13 00:00:00,2020-02-26 00:00:00,0.0,0.0,1.0,0.0,0.0,0.0,0.0,13 days 00:00:00
25,61.00,1,2020-02-14 00:00:00,2020-02-26 00:00:00,1.0,0.0,0.0,0.0,0.0,0.0,0.0,12 days 00:00:00
26,29.00,1,2020-01-24 00:00:00,2020-01-28 00:00:00,0.0,0.0,0.0,0.0,0.0,0.0,0.0,4 days 00:00:00
27,72.00,1,2020-03-09 00:00:00,2020-03-27 00:00:00,0.0,1.0,0.0,0.0,0.0,0.0,0.0,18 days 00:00:00
28,34.00,1,2020-03-09 00:00:00,2020-03-15 00:00:00,1.0,0.0,0.0,0.0,0.0,0.0,0.0,6 days 00:00:00
29,46.00,1,2020-03-09 00:00:00,2020-03-15 00:00:00,1.0,1.0,0.0,0.0,0.0,0.0,0.0,6 days 00:00:00
30,70.00,1,2020-03-09 00:00:00,2020-03-19 00:00:00,1.0,1.0,0.0,1.0,0.0,0.0,0.0,10 days 00:00:00
31,41.00,1,2020-03-09 00:00:00,2020-03-24 00:00:00,1.0,0.0,0.0,0.0,0.0,0.0,0.0,15 days 00:00:00
32,46.00,0,2020-03-09 00:00:00,2020-03-26 00:00:00,0.0,0.0,0.0,0.0,0.0,0.0,0.0,17 days 00:00:00
33,51.00,0,2020-03-09 00:00:00,2020-03-18 00:00:00,1.0,1.0,0.0,0.0,0.0,0.0,0.0,9 days 00:00:00
34,30.00,0,2020-03-09 00:00:00,2020-03-24 00:00:00,0.0,1.0,0.0,1.0,0.0,0.0,0.0,15 days 00:00:00
35,31.00,1,2020-03-09 00:00:00,2020-03-17 00:00:00,0.0,0.0,0.0,0.0,0.0,0.0,0.0,8 days 00:00:00
36,34.00,1,2020-03-10 00:00:00,2020-03-17 00:00:00,0.0,0.0,0.0,0.0,0.0,0.0,0.0,7 days 00:00:00
37,39.00,0,2020-01-24 00:00:00,2020-02-03 00:00:00,1.0,0.0,1.0,0.0,1.0,0.0,0.0,10 days 00:00:00
38,73.00,1,2020-02-02 00:00:00,2020-02-21 00:00:00,0.0,0.0,0.0,0.0,0.0,0.0,0.0,19 days 00:00:00
39,42.00,0,2020-02-04 00:00:00,2020-02-20 00:00:00,1.0,1.0,0.0,0.0,1.0,0.0,0.0,16 days 00:00:00
40,28.00,0,2020-02-03 00:00:00,2020-02-22 00:00:00,1.0,0.0,0.0,1.0,0.0,0.0,0.0,19 days 00:00:00
41,44.00,0,2020-01-21 00:00:00,2020-01-29 00:00:00,1.0,0.0,1.0,0.0,0.0,0.0,0.0,8 days 00:00:00
42,49.00,0,2020-02-06 00:00:00,2020-02-20 00:00:00,0.0,1.0,0.0,0.0,0.0,0.0,0.0,14 days 00:00:00
43,16.00,0,2020-02-06 00:00:00,2020-02-20 00:00:00,1.0,1.0,0.0,0.0,0.0,0.0,0.0,14 days 00:00:00
44,30.00,1,2020-01-15 00:00:00,2020-01-15 00:00:00,1.0,1.0,0.0,1.0,0.0,0.0,0.0,0 days 00:00:00
46,66.00,1,2020-01-23 00:00:00,2020-02-19 00:00:00,1.0,1.0,0.0,0.0,0.0,0.0,0.0,27 days 00:00:00
47,55.00,1,2020-01-24 00:00:00,2020-02-05 00:00:00,1.0,0.0,0.0,0.0,0.0,0.0,0.0,12 days 00:00:00
48,40.00,1,2020-01-25 00:00:00,2020-02-08 00:00:00,1.0,1.0,0.0,0.0,0.0,0.0,0.0,14 days 00:00:00
49,1.00,0,2020-02-08 00:00:00,2020-02-17 00:00:00,0.0,0.0,0.0,0.0,0.0,0.0,0.0,9 days 00:00:00
50,32.00,1,2020-01-17,2020-01-24,1.0,1.0,0.0,0.0,0.0,1.0,0.0,17 days
51,32.00,1,2020-01-17,2020-01-24,1.0,1.0,0.0,0.0,0.0,1.0,0.0,17 days

Memperbaiki tipe data value setiap kolom

In [33]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 50 entries, 0 to 51
Data columns (total 12 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   age                  50 non-null     float64
 1   sex                  50 non-null     int64
 2   date_confirmation    50 non-null     object
 3   date_recovered       50 non-null     object
 4   Fever                50 non-null     float64
 5   Cough                50 non-null     float64
 6   Fatigue              50 non-null     float64
 7   Sore throat          50 non-null     float64
 8   Runny nose           50 non-null     float64
 9   Shortness of breath  50 non-null     float64
 10  Vomiting             50 non-null     float64
 11  recovery_days        50 non-null     object
dtypes: float64(8), int64(1), object(3)
memory usage: 5.1+ KB

In [34]:
df.drop('recovery_days', axis=1, inplace=True)

In [35]:
df = df.append({'age': 32.00, 'sex': 1, 'date_confirmation': '2020-01-17', 'date_recovered': '2020-01-24', 'Fever': 1.0, 'Cough': 1.0, 'Fatigue': 0.0, 'Sore throat': 0.0, 'Runny nose': 0.0, 'Shortness of breath': 1.0, 'Vomiting': 0.0}, ignore_index=True)
df = df.append({'age': 32.00, 'sex': 1, 'date_confirmation': '2020-01-17', 'date_recovered': '2020-01-24', 'Fever': 1.0, 'Cough': 1.0, 'Fatigue': 0.0, 'Sore throat': 0.0, 'Runny nose': 0.0, 'Shortness of breath': 1.0, 'Vomiting': 0.0}, ignore_index=True)

In [36]:
df.tail()

,age,sex,date_confirmation,date_recovered,Fever,Cough,Fatigue,Sore throat,Runny nose,Shortness of breath,Vomiting
47,1.0,0,2020-02-08 00:00:00,2020-02-17 00:00:00,0.0,0.0,0.0,0.0,0.0,0.0,0.0
48,32.0,1,2020-01-17,2020-01-24,1.0,1.0,0.0,0.0,0.0,1.0,0.0
49,32.0,1,2020-01-17,2020-01-24,1.0,1.0,0.0,0.0,0.0,1.0,0.0
50,32.0,1,2020-01-17,2020-01-24,1.0,1.0,0.0,0.0,0.0,1.0,0.0
51,32.0,1,2020-01-17,2020-01-24,1.0,1.0,0.0,0.0,0.0,1.0,0.0

In [37]:
df['age'] = df['age'].astype('int64')
df['sex'] = df['sex'].astype('int64')
df['date_confirmation'] = df['date_confirmation'].astype('datetime64')
df['date_recovered'] = df['date_recovered'].astype('datetime64')
df['Fever'] = df['Fever'].astype('int64')
df['Cough'] = df['Cough'].astype('int64')
df['Fatigue'] = df['Fatigue'].astype('int64')
df['Sore throat'] = df['Sore throat'].astype('int64')
df['Runny nose'] = df['Runny nose'].astype('int64')
df['Shortness of breath'] = df['Shortness of breath'].astype('int64')
df['Vomiting'] = df['Vomiting'].astype('int64')

In [38]:
df['recovery_days'] = df['date_recovered'] - df['date_confirmation']

In [39]:
df.tail()

,age,sex,date_confirmation,date_recovered,Fever,Cough,Fatigue,Sore throat,Runny nose,Shortness of breath,Vomiting,recovery_days
47,1,0,2020-02-08,2020-02-17,0,0,0,0,0,0,0,9 days
48,32,1,2020-01-17,2020-01-24,1,1,0,0,0,1,0,7 days
49,32,1,2020-01-17,2020-01-24,1,1,0,0,0,1,0,7 days
50,32,1,2020-01-17,2020-01-24,1,1,0,0,0,1,0,7 days
51,32,1,2020-01-17,2020-01-24,1,1,0,0,0,1,0,7 days

In [40]:
df['recovery_days'] = df['recovery_days'].dt.days.astype('int16')

In [41]:
df.tail()

,age,sex,date_confirmation,date_recovered,Fever,Cough,Fatigue,Sore throat,Runny nose,Shortness of breath,Vomiting,recovery_days
47,1,0,2020-02-08,2020-02-17,0,0,0,0,0,0,0,9
48,32,1,2020-01-17,2020-01-24,1,1,0,0,0,1,0,7
49,32,1,2020-01-17,2020-01-24,1,1,0,0,0,1,0,7
50,32,1,2020-01-17,2020-01-24,1,1,0,0,0,1,0,7
51,32,1,2020-01-17,2020-01-24,1,1,0,0,0,1,0,7

In [42]:
df['recovery_days'] = df['recovery_days'].astype('int64')

In [43]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 52 entries, 0 to 51
Data columns (total 12 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   age                  52 non-null     int64
 1   sex                  52 non-null     int64
 2   date_confirmation    52 non-null     datetime64[ns]
 3   date_recovered       52 non-null     datetime64[ns]
 4   Fever                52 non-null     int64
 5   Cough                52 non-null     int64
 6   Fatigue              52 non-null     int64
 7   Sore throat          52 non-null     int64
 8   Runny nose           52 non-null     int64
 9   Shortness of breath  52 non-null     int64
 10  Vomiting             52 non-null     int64
 11  recovery_days        52 non-null     int64
dtypes: datetime64[ns](2), int64(10)
memory usage: 5.0 KB

Mengubah nama kolom

In [44]:
df.rename(
    columns={'age': 'Umur', 'sex': 'Gender', 'date_confirmation': 'Tanggal_konfirmasi', 'date_recovered': 'Tanggal_sembuh', 'Fever': 'Demam', 'Cough': 'Batuk', 'Fatigue': 'Kelelahan', 'Sore throat': 'Sakit_tenggorokan', 'Runny nose': 'Pilek', 'Shortness of breath': 'Sesak_napas', 'Vomiting': 'Muntah', 'recovery_days': 'Lama_hari_sembuh'}, 
    inplace=True,
)

In [45]:
df

,Umur,Gender,Tanggal_konfirmasi,Tanggal_sembuh,Demam,Batuk,Kelelahan,Sakit_tenggorokan,Pilek,Sesak_napas,Muntah,Lama_hari_sembuh
0,44,0,2020-01-21,2020-01-29,1,0,1,0,0,0,0,8
1,39,0,2020-01-24,2020-02-03,1,0,1,0,1,0,0,10
2,30,1,2020-01-15,2020-01-15,1,1,0,1,0,0,0,0
3,66,1,2020-01-23,2020-02-19,1,1,0,0,0,0,0,27
4,40,1,2020-01-25,2020-02-08,1,1,0,0,0,0,0,14
5,33,1,2020-01-27,2020-01-27,1,0,1,1,0,0,0,0
6,1,0,2020-02-08,2020-02-17,0,0,0,0,0,0,0,9
7,30,0,2020-01-24,2020-02-12,1,1,1,0,0,0,0,19
8,31,1,2020-01-24,2020-02-12,1,1,0,0,0,0,0,19
9,29,1,2020-01-24,2020-01-28,0,0,0,0,0,0,0,4
10,55,1,2020-01-24,2020-02-05,1,0,0,0,0,0,0,12
11,73,1,2020-02-02,2020-02-21,0,0,0,0,0,0,0,19
12,42,0,2020-02-04,2020-02-20,1,1,0,0,1,0,0,16
13,28,0,2020-02-03,2020-02-22,1,0,0,1,0,0,0,19
14,49,0,2020-02-06,2020-02-20,0,1,0,0,0,0,0,14
15,16,0,2020-02-06,2020-02-20,1,1,0,0,0,0,0,14
16,29,1,2020-02-06,2020-02-22,1,0,0,0,0,0,0,16
17,55,0,2020-02-09,2020-02-18,1,0,0,0,1,0,0,9
18,0,0,2020-02-11,2020-02-20,0,1,0,0,1,0,0,9
19,50,1,2020-02-13,2020-02-26,0,0,1,0,0,0,0,13
20,61,1,2020-02-14,2020-02-26,1,0,0,0,0,0,0,12
21,55,0,2020-02-09,2020-02-18,1,0,0,0,1,0,0,9
22,0,0,2020-02-11,2020-02-20,0,1,0,0,1,0,0,9
23,50,1,2020-02-13,2020-02-26,0,0,1,0,0,0,0,13
24,61,1,2020-02-14,2020-02-26,1,0,0,0,0,0,0,12
25,29,1,2020-01-24,2020-01-28,0,0,0,0,0,0,0,4
26,72,1,2020-03-09,2020-03-27,0,1,0,0,0,0,0,18
27,34,1,2020-03-09,2020-03-15,1,0,0,0,0,0,0,6
28,46,1,2020-03-09,2020-03-15,1,1,0,0,0,0,0,6
29,70,1,2020-03-09,2020-03-19,1,1,0,1,0,0,0,10
30,41,1,2020-03-09,2020-03-24,1,0,0,0,0,0,0,15
31,46,0,2020-03-09,2020-03-26,0,0,0,0,0,0,0,17
32,51,0,2020-03-09,2020-03-18,1,1,0,0,0,0,0,9
33,30,0,2020-03-09,2020-03-24,0,1,0,1,0,0,0,15
34,31,1,2020-03-09,2020-03-17,0,0,0,0,0,0,0,8
35,34,1,2020-03-10,2020-03-17,0,0,0,0,0,0,0,7
36,39,0,2020-01-24,2020-02-03,1,0,1,0,1,0,0,10
37,73,1,2020-02-02,2020-02-21,0,0,0,0,0,0,0,19
38,42,0,2020-02-04,2020-02-20,1,1,0,0,1,0,0,16
39,28,0,2020-02-03,2020-02-22,1,0,0,1,0,0,0,19
40,44,0,2020-01-21,2020-01-29,1,0,1,0,0,0,0,8
41,49,0,2020-02-06,2020-02-20,0,1,0,0,0,0,0,14
42,16,0,2020-02-06,2020-02-20,1,1,0,0,0,0,0,14
43,30,1,2020-01-15,2020-01-15,1,1,0,1,0,0,0,0
44,66,1,2020-01-23,2020-02-19,1,1,0,0,0,0,0,27
45,55,1,2020-01-24,2020-02-05,1,0,0,0,0,0,0,12
46,40,1,2020-01-25,2020-02-08,1,1,0,0,0,0,0,14
47,1,0,2020-02-08,2020-02-17,0,0,0,0,0,0,0,9
48,32,1,2020-01-17,2020-01-24,1,1,0,0,0,1,0,7
49,32,1,2020-01-17,2020-01-24,1,1,0,0,0,1,0,7
50,32,1,2020-01-17,2020-01-24,1,1,0,0,0,1,0,7
51,32,1,2020-01-17,2020-01-24,1,1,0,0,0,1,0,7

In [46]:
df.to_csv("Data Clean.csv", index=False)